server:
  port: set_the_port_here
  
management:
  context-path: /admin
  security:
    enabled: false

spring:
  application:
    name: configserverexample
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juanlumn/spring-config-repo.git
          search-paths: '*'