server:
  port: 1111

management:
  context-path: /admin
  security:
    enabled: false

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: DEBUG
    com.atsistemas: DEBUG

spring:
  application:
    name: configserverexample
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juanlumn/spring-config-repo.git
          search-paths: '*'